# Actually Configration

[storage]
database = "./data.db"
actualDataDir = "./actual-data"

[payeeTransformation]
enabled = false
openAiApiKey = "<openAiKey>"

[import]
importUncheckedTransactions = true

[[actualServers]]
serverUrl = "http://localhost:5006"
serverPassword = "<password>"

[[actualServers.budgets]]
syncId = "<syncId>"

[actualServers.budgets.e2eEncryption]
enabled = false
password = ""

[actualServers.budgets.accountMapping]
# The key is either the account name, or the account number of a MoneyMoney account
# The value is the account name or the account id of the Actual account
"<monMonAcc>" = "<actualAcc>"
