name: 'Bug report'
description: 'Report a problem so we can keep Actual MoneyMoney stable.'
title: 'bug: <short summary>'
labels:
    - bug
    - needs-triage
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to improve Actual MoneyMoney! CodeRabbit's reviewers triage incoming bugs using
              the details you provide below, so please answer every question thoroughly.
    - type: checkboxes
      id: vetting
      attributes:
          label: Pre-flight checklist
          description: Confirm each item before submitting.
          options:
              - label: I have searched existing issues (including closed ones) and did not find a match.
                required: true
              - label: I am using a supported version of Actual MoneyMoney and Actual Budget, or I have reproduced the bug on the latest release.
                required: true
              - label: I have reviewed the troubleshooting checklist in the CodeRabbit docs and ruled out upstream outages.
                required: false
    - type: textarea
      id: summary
      attributes:
          label: Summary
          description: What is broken? Keep it brief and factual.
          placeholder: 'Sync fails when downloading accounts created after 2024-04-01.'
      validations:
          required: true
    - type: textarea
      id: reproduction
      attributes:
          label: Steps to reproduce
          description: List the minimal steps someone else can follow to reproduce this bug. Include configuration snippets if relevant.
          placeholder: |-
              1. Configure the importer with...
              2. Run `actual-moneymoney import`
              3. Observe ...
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: Expected behaviour
          description: Describe what you expected to happen.
      validations:
          required: true
    - type: textarea
      id: actual
      attributes:
          label: Actual behaviour
          description: Describe what actually happened. Include error messages, stack traces, and screenshots if possible.
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Logs and diagnostics
          description: Provide relevant command output. Mask secrets before sharing and enable the CodeRabbit masking options in your configuration.
          render: shell
    - type: textarea
      id: environment
      attributes:
          label: Environment details
          description: Mention the OS, Node.js version, Actual MoneyMoney version, and any custom configuration that could be relevant.
          placeholder: |-
              - OS: macOS 14.3.1 (Apple Silicon)
              - Node.js: 20.11.1
              - Actual MoneyMoney: v0.7.0
              - Actual Budget server: 24.1.0
              - MoneyMoney build: 2.4.27
              - CLI flags/env vars: ...
      validations:
          required: true
    - type: textarea
      id: impact
      attributes:
          label: Impact and urgency
          description: How does this bug affect your workflow? Let us know if you are blocked.
      validations:
          required: true
    - type: textarea
      id: mitigation
      attributes:
          label: Workarounds tried
          description: Share anything you attempted to mitigate the issue, even if it failed. This helps us avoid duplicated ideas.
    - type: textarea
      id: extra
      attributes:
          label: Additional context
          description: Anything else we should know?
