blank_issues_enabled: true
contact_links:
    - name: Security vulnerabilities
      url: https://github.com/1cu/actual-moneymoney/security/advisories/new
      about: Please report security issues privately so we can coordinate a fix before disclosure.
    - name: Questions & support
      url: https://github.com/1cu/actual-moneymoney/issues/new
      about: Open an issue with the "question" label if you need help deciding which template to use.
