blank_issues_enabled: false
contact_links:
    - name: Security vulnerabilities
      url: https://github.com/1cu/actual-moneymoney/security/advisories/new
      about: Please report security issues privately so we can coordinate a fix before disclosure.
    - name: Questions & support
      url: https://github.com/1cu/actual-moneymoney/issues/new?template=question.yml
      about: Use the question form to open a pre-labeled issue for help from the maintainers.
