name: Auto-merge Dependabot PRs

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    auto-merge:
        if: github.actor == 'dependabot[bot]'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Auto-merge minor and patch updates
              uses: fastify/github-action-merge-dependabot@v3
              with:
                  target: minor
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  merge-method: merge