name: ci
on:
    push:
        branches:
            - main
    pull_request:
jobs:
    quality:
        name: Node ${{ matrix.node-version }} - ${{ matrix.task }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version:
                    - 20
                    - 22
                    - 24
                task:
                    - lint
                    - typecheck
                    - build
                    - test
        steps:
            - uses: actions/checkout@v5
            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: ESLint
              if: matrix.task == 'lint'
              run: npm run lint:eslint
            - name: Complexity budget
              if: matrix.task == 'lint'
              run: npm run lint:complexity
            - name: Prettier
              if: matrix.task == 'lint'
              run: npm run lint:prettier
            - name: Type check
              if: matrix.task == 'typecheck'
              run: npm run typecheck
            - name: Build
              if: matrix.task == 'build'
              run: npm run build
            - name: Run tests
              if: matrix.task == 'test'
              run: npm test

    commitlint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: 20

            - name: Print versions
              run: |
                  git --version
                  node --version
                  npm --version
                  npx commitlint --version

            - name: Install dependencies
              run: npm ci

            - name: Validate current commit (last commit) with commitlint
              if: github.event_name == 'push'
              run: npx commitlint --last --verbose

            - name: Validate PR commits with commitlint
              if: github.event_name == 'pull_request'
              run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
