name: release
on:
    push:
        branches:
            - main
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Node
              uses: actions/setup-node@v5
              with:
                  node-version: '20.9.0'

            - name: Install dependencies
              run: npm install

            - name: Lint with ESLint
              run: npm run lint:eslint

            - name: Lint with Prettier
              run: npm run lint:prettier

            - name: Type check
              run: npm run typecheck

            - name: Run tests
              run: npm test

            - name: Build
              run: npm run build

            - name: Configure Git
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Semantic Release
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
